### PR TITLE
currently pandocomatic errors using certain options 

### PR DESCRIPTION
**Pull request by iandol**
There is mixed use of - and _ in the yaml option lists — standardise to use hyphens, needs a change to pandocomatic too...

### CODE REVIEW

**Comment by htdebeer** [comment]
I used the underscore variants because of the Ruby style convention to use [snake case names](https://github.com/bbatsov/ruby-style-guide#naming) for methods. There will be confusion either way: for Rubyists, dashes are confusing, and for non-Rubyists underscores are. I suppose we could support both variants?

**Comment by iandol** [comment]
OK, this is an internal issue and doesn't affect the end user so if you prefer snake_case as long as the naming in the YAML file is consistent then I think the mismatch with the pandoc - is fine.

**Comment by htdebeer** [comment]
Dear Ian,

On Wed, Jul 05, 2017 at 08:02:33AM +0000, Ian wrote:
> OK, this is an internal issue and doesn't affect the end user so if you prefer
> snake_case as long as the naming in the YAML file is consistent then I think
> the mismatch with the pandoc - is fine.

Actually, I agreed with you that the underscores and dashes can be confusing
depending on the user of paru. Yesterday I tried implementing using both
variants for method names, but then I discovered that Ruby just does not allow
dashes in method names.

I unmerged your fixes and updated the various configuration file to only
contain underscores. It might be something to stress in the documentation,
though: all mutli-word command line options use underscores instead of dashes
to separate words when using the option as a paru method.

Anyway, thanks for your input,

with kind regards,
-- 
Huub de Beer

email   :   huub@heerdebeer.org
www     :   http://heerdebeer.org

**Comment by iandol** [comment]
Yes, it is probably worth mentioning somewhere. I didn't realise you could use options as methods, I suppose that is some sort of meta-programming thing? I really need to learn Ruby properly... 😬

**Comment by htdebeer** [comment]
That's what makes Ruby (and similar languages) so much fun! The metaprogramming part of paru is located [here](https://github.com/htdebeer/paru/blob/master/lib/paru/pandoc.rb#L234). It basically reads the options, and for each option it creates a method.

**Pull request merged**
